import Head from 'next/head';
import { FeaturedProducts, HomeCards, HomeMainSection, Navbar, Sidebar, Footer } from '../components';
import { featuredProductsUrl as url } from '../utils/constants';
import axios from 'axios';

export default function Home({featuredProducts}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar />
      <HomeMainSection />
      <FeaturedProducts products={featuredProducts}/>
      <HomeCards />
      <Footer />
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
      const response = await axios(url);
      const featuredProducts = response.data.data;
      return {
          props: {
              featuredProducts
          }
      }
  } catch (error) {
      return {
          props: {
              featuredProducts: null
          }
      }
  }
}